"""Authorization area status (Phase 3C, status/reporting only).

Statuses: PASS, FAIL, NOT CONFIGURED, NOT VERIFIED, INCOMPLETE.
This version never executes runtime authorization checks, so the status is NOT VERIFIED.
The only way the area becomes FAIL is the presence of ``RT-AUTHZ-*`` findings in the
report (reserved namespace for future imported results; none are generated here).
This is a coverage status, not a security verdict.

Sub-areas (reporting groundwork for docs/AUTH-SESSION-AUTHORIZATION-DESIGN.md): ``authorization``,
``idor_bola`` and ``tenant_isolation``. Each is always NOT VERIFIED in this version, with
``runtime_checks_executed: false`` and ``credentials_read: false``. Their namespaces (``RT-AUTHZ-*``,
``RT-IDOR-*``, ``RT-TENANT-*``) are reserved; no finding is generated for them, and a sub-area never
becomes PASS or FAIL here.
"""

from __future__ import annotations

from typing import Any

from ..models import Finding

CATEGORY = "authorization"
STATUSES = ("PASS", "FAIL", "NOT CONFIGURED", "NOT VERIFIED", "INCOMPLETE")
SCOPE = ["authorization", "IDOR/BOLA", "tenant isolation"]
REASON = ("Runtime authorization, IDOR/BOLA and tenant-isolation checks are not executed by this Phase 3 runtime "
          "implementation. These areas remain covered only by the Layer 2 source-code security review. "
          "This is a coverage status, not a security verdict.")
REASON_REFUSED = "Safety gate refused the target; nothing was sent. " + REASON

# sub-area key: (label, finding category, reserved namespace)
SUBAREAS = {
    "authorization": ("Authorization", "authorization", "RT-AUTHZ-*"),
    "idor_bola": ("IDOR/BOLA", "idor", "RT-IDOR-*"),
    "tenant_isolation": ("Tenant isolation", "tenant_isolation", "RT-TENANT-*"),
}
CATEGORIES = tuple(category for _, category, _ in SUBAREAS.values())
SUBAREA_REASON = "Not executed by this Phase 3 runtime implementation; no request was sent for this area."


def authz_subareas(findings: list[Finding], refused: bool) -> dict[str, dict[str, Any]]:
    """Per-sub-area coverage status. Always NOT VERIFIED in this version (never PASS/FAIL)."""
    reason = ("Safety gate refused the target; nothing was sent. " if refused else "") + SUBAREA_REASON
    return {
        key: {
            "area": label,
            "status": "NOT VERIFIED",
            "reason": reason,
            "namespace": namespace,
            "runtime_checks_executed": False,
            "credentials_read": False,
            "findings": [f.id for f in findings if f.category == category],   # none are generated by this version
        }
        for key, (label, category, namespace) in SUBAREAS.items()
    }


def authz_area_status(findings: list[Finding], refused: bool) -> dict[str, Any]:
    ids = [f.id for f in findings if f.category == CATEGORY]
    if ids and not refused:
        status, reason = "FAIL", "RT-AUTHZ findings present in this report (imported results)."
    else:
        status, reason = "NOT VERIFIED", REASON_REFUSED if refused else REASON
    return {
        "area": "Authorization",
        "status": status,
        "reason": reason,
        "scope": list(SCOPE),
        "runtime_checks_executed": False,   # no authorization requests are sent by this version
        "credentials_read": False,
        "findings": ids,
        "subareas": authz_subareas(findings, refused),
    }
