"""Authorization area status (Phase 3C reporting & imported results).

Statuses: PASS, FAIL, NOT CONFIGURED, NOT VERIFIED, INCOMPLETE.
When native verification is active under runtime_verification, native execution
results are populated by runtime_security.native.executor and runtime_security.native.authz.
When imported verification is active under verification_results, this module populates
statuses from the external imported evidence.
Without native verification or imported results, the status remains NOT VERIFIED
(a coverage status, not a security verdict).

Sub-areas: authorization, idor_bola, and tenant_isolation.
"""

from __future__ import annotations

from typing import Any

from ..models import Finding
from ..verification import status as vst
from ..verification.report import REASON_IMPORTED, area_fields

CATEGORY = "authorization"
STATUSES = ("PASS", "FAIL", "NOT CONFIGURED", "NOT VERIFIED", "INCOMPLETE")
SCOPE = ["authorization", "IDOR/BOLA", "tenant isolation"]
REASON = ("Runtime authorization, IDOR/BOLA and tenant-isolation checks are not executed by this Phase 3 runtime "
          "implementation. These areas remain covered only by the Layer 2 source-code security review. "
          "This is a coverage status, not a security verdict.")
REASON_REFUSED = "Safety gate refused the target; nothing was sent. " + REASON

# sub-area key: (label, finding category, reserved namespace)
SUBAREAS = {
    "authorization": ("Authorization", "authorization", "RT-AUTHZ-*"),
    "idor_bola": ("IDOR/BOLA", "idor", "RT-IDOR-*"),
    "tenant_isolation": ("Tenant isolation", "tenant_isolation", "RT-TENANT-*"),
}
CATEGORIES = tuple(category for _, category, _ in SUBAREAS.values())
SUBAREA_REASON = "Not executed by this Phase 3 runtime implementation; no request was sent for this area."


def authz_subareas(findings: list[Finding], refused: bool) -> dict[str, dict[str, Any]]:
    """Per-sub-area coverage status. Always NOT VERIFIED in this version (never PASS/FAIL)."""
    reason = ("Safety gate refused the target; nothing was sent. " if refused else "") + SUBAREA_REASON
    return {
        key: {
            "area": label,
            "status": "NOT VERIFIED",
            "reason": reason,
            "namespace": namespace,
            "runtime_checks_executed": False,
            "credentials_read": False,
            "findings": [f.id for f in findings if f.category == category],   # none are generated by this version
        }
        for key, (label, category, namespace) in SUBAREAS.items()
    }


def imported_authz_status(findings: list[Finding], imported: Any) -> dict[str, Any]:
    """Authorization block populated from a configured import (statuses per the verification status rules)."""
    subs = {key: {"area": label, **area_fields(imported, key, findings)} for key, (label, _, _) in SUBAREAS.items()}
    status = vst.aggregate(s["status"] for s in subs.values())
    reason = REASON_IMPORTED if imported.usable else imported.reason
    subarea_sources = {key: s.get("source", "none") for key, s in subs.items()}
    unique_sources = set(subarea_sources.values())
    aggregate_source = next(iter(unique_sources)) if len(unique_sources) == 1 else "mixed"
    return {
        "area": "Authorization",
        "status": status,
        "reason": reason + " Overall status combines the Authorization, IDOR/BOLA and Tenant isolation sub-areas; "
                           "PASS only when all three are PASS.",
        "scope": list(SCOPE),
        "source": "imported",
        "verification_source": aggregate_source,
        "verification_subarea_source": subarea_sources,
        "runtime_checks_executed": any(s["runtime_checks_executed"] for s in subs.values()),
        "credentials_read": False,
        "requests_count": sum(s["requests_count"] for s in subs.values()),
        "findings": [f.id for f in findings if f.category == CATEGORY],
        "subareas": subs,
    }


def authz_area_status(findings: list[Finding], refused: bool, imported: Any = None) -> dict[str, Any]:
    if imported is not None and not refused:
        return imported_authz_status(findings, imported)
    ids = [f.id for f in findings if f.category == CATEGORY]
    if ids and not refused:
        status, reason = "FAIL", "RT-AUTHZ findings present in this report (imported results)."
    else:
        status, reason = "NOT VERIFIED", REASON_REFUSED if refused else REASON
    return {
        "area": "Authorization",
        "status": status,
        "reason": reason,
        "scope": list(SCOPE),
        "runtime_checks_executed": False,   # no authorization requests are sent by this version
        "credentials_read": False,
        "findings": ids,
        "subareas": authz_subareas(findings, refused),
    }
