"""Native Authentication Verification (Design §8, §15, §16, §17).

Implements bounded, deterministic runtime verification for the Authentication area:
- A1: unauthenticated access to protected route (anonymous GET)
- A2: invalid authentication attempt (synthetic invalid secret POST login)
- A3: valid authentication positive control for each declared actor (POST login)
- A4: authenticated access to protected route for primary user (GET)
- A5: logout operation (POST/GET logout)
- A6: reuse of invalidated session after logout (GET protected route)

Guarantees:
- Synthetic identities only (generated by IdentityVault; never real credentials).
- No brute-force, password-spraying, or account enumeration.
- Exactly 1 invalid attempt (A2) and 1 login attempt per declared actor (A3).
- Strictly bounded request count (max 9 requests per run).
- Response classification: allowed, denied, ambiguous, incomplete.
- Evidence records match Design §15 schema (check, actors, method, path, status,
  classification, marker_present, elapsed_ms, fingerprint).
- Deterministic findings RT-AUTH-001, RT-AUTH-002, RT-AUTH-003 with severity HIGH.
- Positive control failure makes the area INCOMPLETE with no findings emitted.
- If logout is not declared, the area can at most be EXECUTED, not PASS.
- Secrets never exposed in findings, evidence, representations, or reports.
"""

from __future__ import annotations

import hashlib
import hmac
import json
import secrets
from typing import Any

from ..config import Config
from ..models import Confidence, Finding, Severity, Status
from ..utils.http import Response
from ..utils.redaction import clean
from .identity import IdentityVault
from .plan import PlannedRequest

AUTH_NAMESPACE = "RT-AUTH-*"


def build_auth_requests(cfg: Config) -> list[PlannedRequest]:
    """Construct deterministic planned requests for native authentication verification (Design §8)."""
    rv = cfg.runtime_verification
    if not rv:
        return []

    actors = rv.actors
    users = [k for k, v in sorted(actors.items()) if v.role == "user"]
    if not users:
        return []
    primary_user = "user_a" if "user_a" in users else users[0]

    protected_route = rv.routes.get("protected")
    if not protected_route:
        return []
    protected_path = protected_route.path
    protected_marker = protected_route.marker.replace("{label}", primary_user)

    login_path = "/login"
    login_method = "POST"
    if cfg.authentication and cfg.authentication.login:
        login_path = cfg.authentication.login.path
        login_method = cfg.authentication.login.method

    has_logout = bool(
        cfg.authentication
        and cfg.authentication.logout
        and cfg.authentication.logout.enabled
    )
    logout_path = "/logout"
    logout_method = "POST"
    if has_logout and cfg.authentication and cfg.authentication.logout:
        logout_path = cfg.authentication.logout.path
        logout_method = cfg.authentication.logout.method

    requests: list[PlannedRequest] = []

    # A1: unauthenticated access (anonymous)
    requests.append(
        PlannedRequest(
            area="authentication",
            check_id="A1",
            method="GET",
            path=protected_path,
            actor="anonymous",
            expected="denied",
            marker=protected_marker,
        )
    )

    # A2: invalid authentication attempt
    requests.append(
        PlannedRequest(
            area="authentication",
            check_id="A2",
            method=login_method,
            path=login_path,
            actor=primary_user,
            expected="rejected",
        )
    )

    # A3: valid authentication per actor in sorted order
    for actor in sorted(actors.keys()):
        requests.append(
            PlannedRequest(
                area="authentication",
                check_id="A3",
                method=login_method,
                path=login_path,
                actor=actor,
                expected="success",
            )
        )

    # A4: authenticated access for primary user
    requests.append(
        PlannedRequest(
            area="authentication",
            check_id="A4",
            method="GET",
            path=protected_path,
            actor=primary_user,
            expected="allowed",
            marker=protected_marker,
        )
    )

    # A5 & A6 if logout declared
    if has_logout:
        requests.append(
            PlannedRequest(
                area="authentication",
                check_id="A5",
                method=logout_method,
                path=logout_path,
                actor=primary_user,
                expected="success",
            )
        )
        requests.append(
            PlannedRequest(
                area="authentication",
                check_id="A6",
                method="GET",
                path=protected_path,
                actor=primary_user,
                expected="denied",
                marker=protected_marker,
            )
        )

    return requests


def extract_session(resp: Response) -> tuple[str | None, str | None]:
    """Extract session cookie and/or bearer token from an HTTP response."""
    cookie_str: str | None = None
    auth_str: str | None = None

    # 1. Cookies from Set-Cookie headers
    cookies = resp.header_all("set-cookie")
    if cookies:
        pairs = []
        for c in cookies:
            part = c.split(";")[0].strip()
            if part and "=" in part:
                pairs.append(part)
        if pairs:
            cookie_str = "; ".join(pairs)

    # 2. Authorization header
    auth_hdr = resp.header("authorization")
    if auth_hdr and auth_hdr.strip():
        auth_str = auth_hdr.strip()

    # 3. JSON body token
    if not auth_str and resp.body:
        try:
            data = json.loads(resp.body)
            if isinstance(data, dict):
                token = (
                    data.get("token")
                    or data.get("access_token")
                    or data.get("session_token")
                    or data.get("jwt")
                )
                if token and isinstance(token, str):
                    auth_str = f"Bearer {token.strip()}"
        except Exception:
            pass

    return cookie_str, auth_str


def is_mfa_challenge(resp: Response) -> bool:
    """Detect if target returned an interactive MFA or CAPTCHA challenge."""
    if resp.header("x-mfa-required") or resp.header("x-captcha-required"):
        return True
    body_lower = resp.body.lower()
    mfa_markers = (
        "mfa_required",
        "mfa-required",
        "totp_required",
        "captcha_required",
        "two_factor_required",
        "2fa_required",
    )
    return any(marker in body_lower for marker in mfa_markers)


def compute_fingerprint(run_hmac_key: bytes, session_str: str | None) -> str | None:
    """Compute 12-char HMAC-SHA256 fingerprint for session identifier without storing value."""
    if not session_str:
        return None
    return hmac.new(run_hmac_key, session_str.encode("utf-8"), hashlib.sha256).hexdigest()[:12]


def make_auth_finding(check_id: str, path: str, status: int, detail: str = "") -> Finding:
    """Construct deterministic Finding for an authentication violation (Design §17)."""
    if check_id == "A1":
        return Finding(
            id="RT-AUTH-001",
            category="authentication",
            severity=Severity.HIGH,
            confidence=Confidence.HIGH,
            title="Unauthenticated access allowed to protected route",
            endpoint=f"GET {path}",
            expected="denied",
            actual="allowed",
            evidence=clean(
                detail or f"Protected marker returned with HTTP status {status} to unauthenticated request",
                300,
            ),
            impact="Protected route is accessible without authentication",
            recommendation="Require authentication before serving protected routes",
            validation="Send unauthenticated GET request to protected route and verify it is rejected",
            status=Status.OPEN,
            source="native-verification",
        )
    elif check_id == "A2":
        return Finding(
            id="RT-AUTH-002",
            category="authentication",
            severity=Severity.HIGH,
            confidence=Confidence.HIGH,
            title="Session issued for invalid authentication credentials",
            endpoint=f"POST {path}",
            expected="rejected, no session issued",
            actual="session issued",
            evidence=clean(
                detail or f"Target returned HTTP status {status} and issued a session for invalid credentials",
                300,
            ),
            impact="Invalid credentials are accepted and grant access",
            recommendation="Reject invalid credentials with 401/403 and do not issue session cookies or tokens",
            validation="POST invalid credentials to login endpoint and verify rejection without session issuance",
            status=Status.OPEN,
            source="native-verification",
        )
    elif check_id == "A6":
        return Finding(
            id="RT-AUTH-003",
            category="authentication",
            severity=Severity.HIGH,
            confidence=Confidence.HIGH,
            title="Session remains valid after logout",
            endpoint=f"GET {path}",
            expected="denied",
            actual="allowed",
            evidence=clean(
                detail or f"Protected marker returned with HTTP status {status} when reusing session after logout",
                300,
            ),
            impact="Logged-out session tokens can still be reused to access protected resources",
            recommendation="Invalidate session tokens and cookies on logout",
            validation="Perform logout and attempt to reuse old session token on protected route",
            status=Status.OPEN,
            source="native-verification",
        )
    raise ValueError(f"Unknown auth check ID for finding: {check_id}")
